### ISSUE TITLE
Failed to open main MPQ file with error 87

### ISSUE THREAD

**Issue by max-bruhn** [tswow/tswow#150] opened 2021-03-17 07:46 UTC
**Describe the bug**
I ran npm run start, after about 5 min i got this error: 
```
Converting Zulgurubtree05.m2
Ok, all done
Reading main 
Failed to open main MPQ file with error 87
Failed to start tswow: Error: Command failed: "bin\mpqbuilder\luaxmlreader.exe" C:\WoW Server\tswow\release-debug\coredata\luaxml_source C:\WoW_Server\wow-3-3-5-a_tswow\Data
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.exec (C:\WoW Server\tswow\tswow\tswow-scripts\util\System.ts:104:36)
    at buildLuaXML (C:\WoW Server\tswow\tswow\tswow-scripts\runtime\MapData.ts:99:14)
    at rebuild (C:\WoW Server\tswow\tswow\tswow-scripts\runtime\MapData.ts:126:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.initialize (C:\WoW Server\tswow\tswow\tswow-scripts\runtime\MapData.ts:135:9)
    at Object.main (C:\WoW Server\tswow\tswow\tswow-scripts\runtime\TSWoW.ts:55:9) {
  status: 87,
  signal: null,
  output: [ null, null, null ],
  pid: 14948,
  stdout: null,
  stderr: null
}
>
```

**To Reproduce**
I'm on Win 10, using VS Code 1.54.3
1. download TSWoW Alpha v0.10 release-debug.7z
2. extract archive
3. change client directory to wow.exe directory
4. npm run start

**Expected behavior**
Expect successful install

**Comment by ihm-tswow** [comment] 2021-03-17 07:59
Known issue in the release (but for some reason the issue is gone?). You can't have spaces in the filepath to your wow installation or server in the alpha release, this should be fixed in the next release.

**Comment by ihm-tswow** [comment] 2021-03-17 08:06
If that still does not fix it (I know of one person who kept getting that error on portuguese windows), you can also manually extract the entire `Interface` folder from your locale MPQs, and place it in coredata, i.e: `coredata/luaxml_source/Interface`.

**Comment by ihm-tswow** [comment] 2021-03-24 09:14
Path errors should be more descriptive: 091cd15b7e5e5345695be8874e5e5e061781060b

Getting second thoughts about trying to support spaces in pathnames
It's not very hard to get it working with tswow tools, I just re-run the build script until nothing errors while i'm in a spaced path, but the amount of weird errors that come up because of it reminded me that: 

1. Every single tswow developer has to use spaces in their own pathnames to always cause those errors to occur, otherwise they'll write new errors for the users that do have them

2. We don't control external tools that might not support them, causing massive headaches because we decided to support it.
I instead suggest we just give more descriptive errors when such paths are found or users attempt to create them

**Closed as completed** 2022-01-27 19:27 UTC
Labels: bug
