### ISSUE TITLE
Compiling on win10 failed, Error: Cannot create a string longer than 0xffffff0 characters

### ISSUE THREAD

**Issue by SouthMemory** [tswow/tswow#844] opened 2024-04-16 18:52 UTC
Error: Cannot create a string longer than 0xffffff0 characters
    at Object.slice (node:buffer:599:37)
    at Buffer.toString (node:buffer:818:14)
    at Object.readFileSync (node:fs:512:41)
    at WFile.readString (C:\Users\zhaolun\Documents\GitHub\tswow\source\tswow-scripts\util\FileTree.ts:345:23)
    at Object.<anonymous> (C:\Users\zhaolun\Documents\GitHub\tswow\source\tswow-scripts\compile\TrinityCore.ts:346:47)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\zhaolun\Documents\GitHub\tswow\build\bootstrap\compile\TrinityCore.js:38:28)
    at _next (C:\Users\zhaolun\Documents\GitHub\tswow\build\bootstrap\compile\TrinityCore.js:56:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
node:child_process:946
    throw err;
    ^

Error: Command failed: node -r source-map-support/register ..\build\bootstrap\compile\CompileTsWow.js  --ignore **/wotlkdata/** --ipaths=../install --bpaths=../build --displayNames --displayTimestamps
    at checkExecSyncError (node:child_process:871:11)
    at Object.execSync (node:child_process:943:15)
    at Object.<anonymous> (C:\Users\zhaolun\Documents\GitHub\tswow\source\build.js:47:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18252,
  stdout: null,
  stderr: null
}

Node.js v18.12.1

code Already up to date, Not knowing What could be the reason?

**Comment by SouthMemory** [comment] 2024-04-18 09:40
Still can't solve this problem.
Compiling on my another computer succeeded, I am thinking maybe i'll reinstall my win10 system

**Comment by SouthMemory** [comment] 2024-04-19 01:13
I had to reinstall my computer as win11, and the problem did not occur again.

**Comment by ihm-tswow** [comment] 2024-09-10 13:41
Looks like this happened when trying to read the trinitycore tdb, and the nodejs version used had a string limit of just under 270mb (the tdb is around 280mb). I would suspect that this was caused by another version of node js being used, or that your version of node js was 32-bit (seems there are still installers for that).

I'll take a guess that it's an environment issue since it disappeared and hasn't to my knowledge been reported since, so i'll close this issue and you can open a new issue if it happens again.

**Closed as completed by ihm-tswow** 2024-09-10 13:41 UTC
Labels: bug
